apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks
  region: ap-south-1  # give proper region names according to what region you are using
nodeGroups:
  - name: node-1
    instanceType: t2.small
    desiredCapacity: 1
    # volumeSize: 8
    ssh:
      allow: true  # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: node-2
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub


#Create cluster using the command

eksctl create cluster -f cluster.yaml